import logging
import json
import numpy as np
from scipy import constants
import pandas as pd

def apply_antenna_pattern(df, sample_rate, beamwidth, scan_rate, sut_az, gain_factor):
    """
    Antenna pattern is generated by the following:
    gain = (sinc(10*angle/beamwidth) - angle/100)^2
    The pattern is then normalized to the gain factor
    """
    scan_rate_rad = scan_rate * np.pi / 180
    sut_az_rad = sut_az * np.pi / 180
    df["timestamp"] = range(len(df)) / sample_rate
    df["angle"] = np.mod(np.mod(sut_az_rad - df["timestamp"] * scan_rate_rad, 2*np.pi) + 2*np.pi, 2*np.pi)
    linear_gain_factor = 10**(gain_factor/10)
    mask = (df["angle"] > np.pi)
    df.loc[mask, "angle"] = df.loc[mask, "angle"] - 2*np.pi
    df["gain"] = (np.sin(10*df["angle"]/beamwidth)/df["angle"] - df["angle"]/100)**2
    df["gain"] = df["gain"] / df["gain"].max() * linear_gain_factor
    df["I"] = df["I"] * df["gain"]
    df["Q"] = df["Q"] * df["gain"]
    df = df.drop(['timestamp', 'angle', 'gain'], axis=1)
    return df

def get_range_loss(range):
    power_multiplier = 1 / (4 * np.pi * range**2)
    return power_multiplier

def calculate_sample_delay(sample_rate_hz, range):
    time_delay = 2 * range / constants.c
    sample_delay = int(time_delay * sample_rate_hz)
    return sample_delay

def get_power_from_db(power_db):
    return 10**(power_db/10)

def apply_power_offset(dataframe, power_linear):
    multiplier = np.sqrt(power_linear)
    dataframe["I"] = dataframe["I"] * multiplier
    dataframe["Q"] = dataframe["Q"] * multiplier
    return dataframe

def add_iq_df(df_1, df_2):
    return df_1.add(df_2, fill_value=0)

def front_fill_samples(df: pd.DataFrame, num_samples):
    zeros_np = np.zeros([num_samples, 2])
    zeros_df = pd.DataFrame(zeros_np, columns = df.columns)
    combined_df = pd.concat([zeros_df, df]).reset_index(drop=True)
    return combined_df

def write_to_hdf(df: pd.DataFrame, filename):
    df.to_hdf(filename, 'df', mode='w')

def read_hdf(filename):
    return pd.read_hdf(filename, "df")

def import_json(file: str) -> dict:
    """
    Helper method to import data from a file as a json object
    """
    output = {}
    try:
        with open(file, 'r', encoding='utf-8') as filereader:
            output = json.load(filereader)
    except ValueError as err:
        logging.error("JSON parsing error: %s", err)
    return output