# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ppi_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ppi_gui(object):
    def setupUi(self, ppi_gui):
        ppi_gui.setObjectName("ppi_gui")
        ppi_gui.resize(1358, 1018)
        ppi_gui.setStyleSheet("/*\n"
"ElegantDark Style Sheet for QT Applications\n"
"Author: Jaime A. Quiroga P.\n"
"Company: GTRONICK\n"
"Last updated: 17/04/2018\n"
"Available at: https://github.com/GTRONICK/QSS/blob/master/ElegantDark.qss\n"
"*/\n"
"QMainWindow {\n"
"    background-color:rgb(82, 82, 82);\n"
"}\n"
"QTextEdit {\n"
"    background-color:rgb(42, 42, 42);\n"
"    color: rgb(0, 255, 0);\n"
"}\n"
"QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(0, 0, 0);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(57, 57, 57, 255), stop:1 rgba(77, 77, 77, 255));\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(100, 100, 100);\n"
"    selection-background-color: rgb(187, 187, 187);\n"
"    selection-color: rgb(60, 63, 65);\n"
"}\n"
"QSpinBox {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(100, 100, 100);\n"
"    selection-background-color: rgb(187, 187, 187);\n"
"    selection-color: rgb(60, 63, 65);\n"
"}\n"
"QDoubleSpinBox {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(100, 100, 100);\n"
"    selection-background-color: rgb(187, 187, 187);\n"
"    selection-color: rgb(60, 63, 65);\n"
"}\n"
"QLabel {\n"
"    color:rgb(255,255,255);    \n"
"}\n"
"QGroupBox {\n"
"    color:rgb(255,255,255);    \n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    background-color:rgb(77,77,77);\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
"    border-radius: 5px;\n"
"}\n"
"QMenuBar {\n"
"    background:rgb(82, 82, 82);\n"
"}\n"
"QMenuBar::item {\n"
"    color:rgb(223,219,210);\n"
"    spacing: 3px;\n"
"    padding: 1px 4px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background:rgb(115, 115, 115);\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    border-width:2px;\n"
"    border-style:solid;\n"
"    padding-left:18px;\n"
"    padding-right:8px;\n"
"    padding-top:2px;\n"
"    padding-bottom:3px;\n"
"    background:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(78,78,78);\n"
"    padding-left:20px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:10px;\n"
"}\n"
"QMenu{\n"
"    background-color:rgb(78,78,78);\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:rgb(247,246,246);\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(77,77,77);\n"
"        background-color:rgb(101,101,101);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    padding:2px;\n"
"    color:rgb(250,250,250);\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"      border-top-right-radius:4px;\n"
"   border-top-left-radius:4px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-bottom-color: rgb(101,101,101);\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      background-color:rgb(101,101,101);\n"
"      margin-left: 0px;\n"
"      margin-right: 1px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"        margin-top: 1px;\n"
"        margin-right: 1px;\n"
"}\n"
"QCheckBox {\n"
"    color:rgb(223,219,210);\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 150), stop:1 rgba(93, 103, 113, 150));\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: rgb(180,180,180);\n"
"      background-color:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QStatusBar {\n"
"    color:rgb(240,240,240);\n"
"}\n"
"PyQtGraphWidget {\n"
"    color:rgb(255,255,255)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ppi_gui)
        self.centralwidget.setObjectName("centralwidget")
        self.gb_plot_control = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_plot_control.setGeometry(QtCore.QRect(10, 510, 351, 261))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_plot_control.setFont(font)
        self.gb_plot_control.setObjectName("gb_plot_control")
        self.lbl_colorbar_intensity = QtWidgets.QLabel(self.gb_plot_control)
        self.lbl_colorbar_intensity.setGeometry(QtCore.QRect(90, 130, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_colorbar_intensity.setFont(font)
        self.lbl_colorbar_intensity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_colorbar_intensity.setObjectName("lbl_colorbar_intensity")
        self.le_cbar_min = QtWidgets.QLineEdit(self.gb_plot_control)
        self.le_cbar_min.setEnabled(True)
        self.le_cbar_min.setGeometry(QtCore.QRect(160, 160, 91, 20))
        self.le_cbar_min.setObjectName("le_cbar_min")
        self.lbl_cbar_min = QtWidgets.QLabel(self.gb_plot_control)
        self.lbl_cbar_min.setGeometry(QtCore.QRect(20, 160, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_cbar_min.setFont(font)
        self.lbl_cbar_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_cbar_min.setObjectName("lbl_cbar_min")
        self.le_cbar_max = QtWidgets.QLineEdit(self.gb_plot_control)
        self.le_cbar_max.setEnabled(True)
        self.le_cbar_max.setGeometry(QtCore.QRect(160, 190, 91, 20))
        self.le_cbar_max.setObjectName("le_cbar_max")
        self.lbl_cbar_max = QtWidgets.QLabel(self.gb_plot_control)
        self.lbl_cbar_max.setGeometry(QtCore.QRect(20, 190, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_cbar_max.setFont(font)
        self.lbl_cbar_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_cbar_max.setObjectName("lbl_cbar_max")
        self.lbl_cbar_min_units = QtWidgets.QLabel(self.gb_plot_control)
        self.lbl_cbar_min_units.setGeometry(QtCore.QRect(260, 160, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_cbar_min_units.setFont(font)
        self.lbl_cbar_min_units.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_cbar_min_units.setObjectName("lbl_cbar_min_units")
        self.lbl_cbar_max_units = QtWidgets.QLabel(self.gb_plot_control)
        self.lbl_cbar_max_units.setGeometry(QtCore.QRect(260, 190, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_cbar_max_units.setFont(font)
        self.lbl_cbar_max_units.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_cbar_max_units.setObjectName("lbl_cbar_max_units")
        self.pb_cbar_apply = QtWidgets.QPushButton(self.gb_plot_control)
        self.pb_cbar_apply.setEnabled(True)
        self.pb_cbar_apply.setGeometry(QtCore.QRect(110, 220, 91, 31))
        self.pb_cbar_apply.setObjectName("pb_cbar_apply")
        self.lbl_max_range_units = QtWidgets.QLabel(self.gb_plot_control)
        self.lbl_max_range_units.setGeometry(QtCore.QRect(260, 90, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_max_range_units.setFont(font)
        self.lbl_max_range_units.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_max_range_units.setObjectName("lbl_max_range_units")
        self.le_max_range = QtWidgets.QLineEdit(self.gb_plot_control)
        self.le_max_range.setEnabled(True)
        self.le_max_range.setGeometry(QtCore.QRect(160, 90, 91, 20))
        self.le_max_range.setObjectName("le_max_range")
        self.lbl_max_range = QtWidgets.QLabel(self.gb_plot_control)
        self.lbl_max_range.setGeometry(QtCore.QRect(20, 90, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_max_range.setFont(font)
        self.lbl_max_range.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_max_range.setObjectName("lbl_max_range")
        self.lbl_range_bin_size = QtWidgets.QLabel(self.gb_plot_control)
        self.lbl_range_bin_size.setGeometry(QtCore.QRect(20, 60, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_range_bin_size.setFont(font)
        self.lbl_range_bin_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_range_bin_size.setObjectName("lbl_range_bin_size")
        self.lbl_range_bin_size_units = QtWidgets.QLabel(self.gb_plot_control)
        self.lbl_range_bin_size_units.setGeometry(QtCore.QRect(260, 60, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_range_bin_size_units.setFont(font)
        self.lbl_range_bin_size_units.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_range_bin_size_units.setObjectName("lbl_range_bin_size_units")
        self.le_range_bin_size = QtWidgets.QLineEdit(self.gb_plot_control)
        self.le_range_bin_size.setEnabled(False)
        self.le_range_bin_size.setGeometry(QtCore.QRect(160, 60, 91, 20))
        self.le_range_bin_size.setObjectName("le_range_bin_size")
        self.le_az_resolution = QtWidgets.QLineEdit(self.gb_plot_control)
        self.le_az_resolution.setEnabled(False)
        self.le_az_resolution.setGeometry(QtCore.QRect(160, 30, 91, 20))
        self.le_az_resolution.setObjectName("le_az_resolution")
        self.lbl_az_resolution = QtWidgets.QLabel(self.gb_plot_control)
        self.lbl_az_resolution.setGeometry(QtCore.QRect(10, 30, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_az_resolution.setFont(font)
        self.lbl_az_resolution.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_az_resolution.setObjectName("lbl_az_resolution")
        self.lbl_az_resolution_units = QtWidgets.QLabel(self.gb_plot_control)
        self.lbl_az_resolution_units.setGeometry(QtCore.QRect(260, 30, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_az_resolution_units.setFont(font)
        self.lbl_az_resolution_units.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_az_resolution_units.setObjectName("lbl_az_resolution_units")
        self.frame_time_plot = QtWidgets.QFrame(self.centralwidget)
        self.frame_time_plot.setGeometry(QtCore.QRect(370, 10, 981, 981))
        self.frame_time_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_time_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_time_plot.setObjectName("frame_time_plot")
        self.widget_ppi_plot = MplWidget(self.frame_time_plot)
        self.widget_ppi_plot.setGeometry(QtCore.QRect(10, 10, 961, 961))
        self.widget_ppi_plot.setObjectName("widget_ppi_plot")
        self.gb_playback_control = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_playback_control.setGeometry(QtCore.QRect(10, 10, 351, 341))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_playback_control.setFont(font)
        self.gb_playback_control.setObjectName("gb_playback_control")
        self.pb_play = QtWidgets.QPushButton(self.gb_playback_control)
        self.pb_play.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.pb_play.setObjectName("pb_play")
        self.lbl_az_step_size = QtWidgets.QLabel(self.gb_playback_control)
        self.lbl_az_step_size.setGeometry(QtCore.QRect(60, 180, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_az_step_size.setFont(font)
        self.lbl_az_step_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_az_step_size.setObjectName("lbl_az_step_size")
        self.pb_load_scenario = QtWidgets.QPushButton(self.gb_playback_control)
        self.pb_load_scenario.setGeometry(QtCore.QRect(20, 40, 141, 41))
        self.pb_load_scenario.setObjectName("pb_load_scenario")
        self.le_selected_file = QtWidgets.QLineEdit(self.gb_playback_control)
        self.le_selected_file.setEnabled(False)
        self.le_selected_file.setGeometry(QtCore.QRect(170, 50, 161, 20))
        self.le_selected_file.setObjectName("le_selected_file")
        self.pb_pause = QtWidgets.QPushButton(self.gb_playback_control)
        self.pb_pause.setEnabled(False)
        self.pb_pause.setGeometry(QtCore.QRect(130, 130, 91, 31))
        self.pb_pause.setObjectName("pb_pause")
        self.pb_reset = QtWidgets.QPushButton(self.gb_playback_control)
        self.pb_reset.setEnabled(False)
        self.pb_reset.setGeometry(QtCore.QRect(240, 130, 91, 31))
        self.pb_reset.setObjectName("pb_reset")
        self.line = QtWidgets.QFrame(self.gb_playback_control)
        self.line.setGeometry(QtCore.QRect(20, 100, 311, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pb_skip_backward = QtWidgets.QPushButton(self.gb_playback_control)
        self.pb_skip_backward.setEnabled(True)
        self.pb_skip_backward.setGeometry(QtCore.QRect(20, 280, 91, 31))
        self.pb_skip_backward.setObjectName("pb_skip_backward")
        self.pb_skip_forward = QtWidgets.QPushButton(self.gb_playback_control)
        self.pb_skip_forward.setEnabled(True)
        self.pb_skip_forward.setGeometry(QtCore.QRect(240, 280, 91, 31))
        self.pb_skip_forward.setObjectName("pb_skip_forward")
        self.lbl_increment = QtWidgets.QLabel(self.gb_playback_control)
        self.lbl_increment.setGeometry(QtCore.QRect(130, 270, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_increment.setFont(font)
        self.lbl_increment.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_increment.setObjectName("lbl_increment")
        self.le_increment = QtWidgets.QLineEdit(self.gb_playback_control)
        self.le_increment.setEnabled(True)
        self.le_increment.setGeometry(QtCore.QRect(140, 300, 61, 20))
        self.le_increment.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_increment.setObjectName("le_increment")
        self.lbl_increment_units = QtWidgets.QLabel(self.gb_playback_control)
        self.lbl_increment_units.setGeometry(QtCore.QRect(210, 300, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_increment_units.setFont(font)
        self.lbl_increment_units.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_increment_units.setObjectName("lbl_increment_units")
        self.line_2 = QtWidgets.QFrame(self.gb_playback_control)
        self.line_2.setGeometry(QtCore.QRect(20, 250, 311, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.le_az_step_size = QtWidgets.QLineEdit(self.gb_playback_control)
        self.le_az_step_size.setEnabled(True)
        self.le_az_step_size.setGeometry(QtCore.QRect(180, 180, 91, 20))
        self.le_az_step_size.setObjectName("le_az_step_size")
        self.lbl_az_step_size_units = QtWidgets.QLabel(self.gb_playback_control)
        self.lbl_az_step_size_units.setGeometry(QtCore.QRect(280, 180, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_az_step_size_units.setFont(font)
        self.lbl_az_step_size_units.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_az_step_size_units.setObjectName("lbl_az_step_size_units")
        self.pb_az_step_apply = QtWidgets.QPushButton(self.gb_playback_control)
        self.pb_az_step_apply.setEnabled(True)
        self.pb_az_step_apply.setGeometry(QtCore.QRect(120, 210, 91, 31))
        self.pb_az_step_apply.setObjectName("pb_az_step_apply")
        self.gb_scenario_data = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_scenario_data.setGeometry(QtCore.QRect(10, 360, 351, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_scenario_data.setFont(font)
        self.gb_scenario_data.setObjectName("gb_scenario_data")
        self.lbl_current_time = QtWidgets.QLabel(self.gb_scenario_data)
        self.lbl_current_time.setGeometry(QtCore.QRect(20, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_current_time.setFont(font)
        self.lbl_current_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_current_time.setObjectName("lbl_current_time")
        self.le_current_time = QtWidgets.QLineEdit(self.gb_scenario_data)
        self.le_current_time.setEnabled(False)
        self.le_current_time.setGeometry(QtCore.QRect(120, 30, 161, 20))
        self.le_current_time.setText("")
        self.le_current_time.setObjectName("le_current_time")
        self.pb_seek_to_time = QtWidgets.QPushButton(self.gb_scenario_data)
        self.pb_seek_to_time.setEnabled(True)
        self.pb_seek_to_time.setGeometry(QtCore.QRect(80, 95, 91, 31))
        self.pb_seek_to_time.setObjectName("pb_seek_to_time")
        self.lbl_scenario_length = QtWidgets.QLabel(self.gb_scenario_data)
        self.lbl_scenario_length.setGeometry(QtCore.QRect(20, 60, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_scenario_length.setFont(font)
        self.lbl_scenario_length.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_scenario_length.setObjectName("lbl_scenario_length")
        self.le_scenario_length = QtWidgets.QLineEdit(self.gb_scenario_data)
        self.le_scenario_length.setEnabled(False)
        self.le_scenario_length.setGeometry(QtCore.QRect(120, 60, 161, 20))
        self.le_scenario_length.setText("")
        self.le_scenario_length.setObjectName("le_scenario_length")
        self.le_seek_to_time = QtWidgets.QLineEdit(self.gb_scenario_data)
        self.le_seek_to_time.setEnabled(True)
        self.le_seek_to_time.setGeometry(QtCore.QRect(190, 100, 91, 20))
        self.le_seek_to_time.setObjectName("le_seek_to_time")
        self.lbl_current_time_units = QtWidgets.QLabel(self.gb_scenario_data)
        self.lbl_current_time_units.setGeometry(QtCore.QRect(290, 30, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_current_time_units.setFont(font)
        self.lbl_current_time_units.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_current_time_units.setObjectName("lbl_current_time_units")
        self.lbl_scenario_length_units = QtWidgets.QLabel(self.gb_scenario_data)
        self.lbl_scenario_length_units.setGeometry(QtCore.QRect(290, 60, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_scenario_length_units.setFont(font)
        self.lbl_scenario_length_units.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_scenario_length_units.setObjectName("lbl_scenario_length_units")
        self.lbl_seek_to_time_units = QtWidgets.QLabel(self.gb_scenario_data)
        self.lbl_seek_to_time_units.setGeometry(QtCore.QRect(290, 100, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_seek_to_time_units.setFont(font)
        self.lbl_seek_to_time_units.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_seek_to_time_units.setObjectName("lbl_seek_to_time_units")
        ppi_gui.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ppi_gui)
        self.statusbar.setObjectName("statusbar")
        ppi_gui.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(ppi_gui)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(ppi_gui)
        self.actionSave.setObjectName("actionSave")

        self.retranslateUi(ppi_gui)
        QtCore.QMetaObject.connectSlotsByName(ppi_gui)

    def retranslateUi(self, ppi_gui):
        _translate = QtCore.QCoreApplication.translate
        ppi_gui.setWindowTitle(_translate("ppi_gui", "PPI Display"))
        self.gb_plot_control.setTitle(_translate("ppi_gui", "PPI Control"))
        self.lbl_colorbar_intensity.setText(_translate("ppi_gui", "Colorbar Intensity"))
        self.le_cbar_min.setText(_translate("ppi_gui", "-100"))
        self.lbl_cbar_min.setText(_translate("ppi_gui", "Colorbar Minimum"))
        self.le_cbar_max.setText(_translate("ppi_gui", "0"))
        self.lbl_cbar_max.setText(_translate("ppi_gui", "Colorbar Maximum"))
        self.lbl_cbar_min_units.setText(_translate("ppi_gui", "dBm"))
        self.lbl_cbar_max_units.setText(_translate("ppi_gui", "dBm"))
        self.pb_cbar_apply.setText(_translate("ppi_gui", "Apply"))
        self.lbl_max_range_units.setText(_translate("ppi_gui", "m"))
        self.le_max_range.setText(_translate("ppi_gui", "0"))
        self.lbl_max_range.setText(_translate("ppi_gui", "Maximum Range"))
        self.lbl_range_bin_size.setText(_translate("ppi_gui", "Range Bin Size"))
        self.lbl_range_bin_size_units.setText(_translate("ppi_gui", "m"))
        self.le_range_bin_size.setText(_translate("ppi_gui", "0"))
        self.le_az_resolution.setText(_translate("ppi_gui", "0"))
        self.lbl_az_resolution.setText(_translate("ppi_gui", "Az Scan Resolution"))
        self.lbl_az_resolution_units.setText(_translate("ppi_gui", "°"))
        self.gb_playback_control.setTitle(_translate("ppi_gui", "Playback Control"))
        self.pb_play.setText(_translate("ppi_gui", "Play"))
        self.lbl_az_step_size.setText(_translate("ppi_gui", "Az Step Size"))
        self.pb_load_scenario.setText(_translate("ppi_gui", "Load Scenario"))
        self.le_selected_file.setText(_translate("ppi_gui", "Select a file..."))
        self.pb_pause.setText(_translate("ppi_gui", "Pause"))
        self.pb_reset.setText(_translate("ppi_gui", "Reset"))
        self.pb_skip_backward.setText(_translate("ppi_gui", "Skip Backward"))
        self.pb_skip_forward.setText(_translate("ppi_gui", "Skip Forward"))
        self.lbl_increment.setText(_translate("ppi_gui", "Increment"))
        self.le_increment.setText(_translate("ppi_gui", "1"))
        self.lbl_increment_units.setText(_translate("ppi_gui", "s"))
        self.le_az_step_size.setText(_translate("ppi_gui", "45"))
        self.lbl_az_step_size_units.setText(_translate("ppi_gui", "deg"))
        self.pb_az_step_apply.setText(_translate("ppi_gui", "Apply"))
        self.gb_scenario_data.setTitle(_translate("ppi_gui", "Scenario Data"))
        self.lbl_current_time.setText(_translate("ppi_gui", "Current Time"))
        self.pb_seek_to_time.setText(_translate("ppi_gui", "Seek To Time"))
        self.lbl_scenario_length.setText(_translate("ppi_gui", "Scenario Length"))
        self.le_seek_to_time.setText(_translate("ppi_gui", "0"))
        self.lbl_current_time_units.setText(_translate("ppi_gui", "s"))
        self.lbl_scenario_length_units.setText(_translate("ppi_gui", "s"))
        self.lbl_seek_to_time_units.setText(_translate("ppi_gui", "s"))
        self.actionLoad.setText(_translate("ppi_gui", "Load"))
        self.actionSave.setText(_translate("ppi_gui", "Save"))
from gui.mplwidget import MplWidget
